# Generated by Django 3.2.7 on 2021-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_data_consulta_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(verbose_name='Data do agendamento'),
        ),
    ]
