# Generated by Django 3.2.7 on 2021-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_consulta_data_agendamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['dia']},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['agenda', 'horario']},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do agendamento'),
        ),
    ]
